/*用户表*/
CREATE TABLE USER
(
    ID VARCHAR(32) NOT NULL,
    NAME VARCHAR(100),
    SEX  INT,
    CODE VARCHAR(100),
    ACCOUNT VARCHAR(100),
    PASSWORD VARCHAR(100),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(100),
    ORG_ID VARCHAR(32),
    ADMIN char(1),
    ACTIVE INT,
    VERSION INT,
    CREATE_TIME DATETIME,
    UPDATE_TIME DATETIME,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    REMARKS VARCHAR(1000),
    PRIMARY KEY (ID)
);

/*机构表*/
CREATE TABLE ORGANIZATION
(
    ID VARCHAR(32) NOT NULL,
    NAME VARCHAR(100),
    CODE VARCHAR(100),
    PARENT_ID VARCHAR(32),
    ACTIVE INT,
    VERSION INT,
    CREATE_TIME DATETIME,
    UPDATE_TIME DATETIME,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    REMARKS VARCHAR(1000),
    PRIMARY KEY (ID)
);

/*雇员表*/
CREATE TABLE EMPLOYEE
(
    ID VARCHAR(32) NOT NULL,
    NAME VARCHAR(100),
    CODE VARCHAR(100),
    SEX    INT,
    AGE    INT,
    IDCARD VARCHAR(50),
    BIRTH_DATE DATETIME,
    ORG_ID VARCHAR(32),
    ACTIVE INT,
    VERSION INT,
    CREATE_TIME DATETIME,
    UPDATE_TIME DATETIME,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    REMARKS VARCHAR(1000),
    PRIMARY KEY (ID)
);

/*终端表*/
CREATE TABLE TERMINAL
(
    ID VARCHAR(32) NOT NULL,
    NAME VARCHAR(100),
    CODE VARCHAR(100),
    ORG_ID VARCHAR(32),
    STYLE_ID VARCHAR(32),
    IPADDR VARCHAR(100),
    LOCATION VARCHAR(100),
    HEARTBEAT DATETIME,
    STATUS char(1),
    ACTIVE INT,
    VERSION INT,
    CREATE_TIME DATETIME,
    UPDATE_TIME DATETIME,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    REMARKS VARCHAR(1000),
    PRIMARY KEY (ID)
);

/*终端类别表*/
CREATE TABLE STYLE
(
    ID VARCHAR(32) NOT NULL,
    NAME VARCHAR(100),
    CODE VARCHAR(100),
    TYPE INT,
    ACTIVE INT,
    VERSION INT,
    CREATE_TIME DATETIME,
    UPDATE_TIME DATETIME,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    REMARKS VARCHAR(1000),
    PRIMARY KEY (ID)
);

/*权限表*/
CREATE TABLE PERMISSION
(
    ID VARCHAR(32) NOT NULL,
    NAME VARCHAR(100),
    CODE VARCHAR(100),
    URL VARCHAR(100),
    PARENT_ID VARCHAR(32),
    ACTIVE INT,
    VERSION INT,
    CREATE_TIME DATETIME,
    UPDATE_TIME DATETIME,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    REMARKS VARCHAR(1000),
    PRIMARY KEY (ID)
);

/*角色表*/
CREATE TABLE ROLE
(
    ID VARCHAR(32) NOT NULL,
    NAME VARCHAR(100),
    CODE VARCHAR(100),
    ACTIVE INT,
    VERSION INT,
    CREATE_TIME DATETIME,
    UPDATE_TIME DATETIME,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    REMARKS VARCHAR(1000),
    PRIMARY KEY (ID)
);

/*角色权限表*/
CREATE TABLE ROLE_PERMISSION
(
	ID VARCHAR(32) NOT NULL,
    ROLE_ID VARCHAR(32) NOT NULL,
    PERMISSION_ID VARCHAR(32) NOT NULL,
    ACTIVE INT,
    VERSION INT,
    CREATE_TIME DATETIME,
    UPDATE_TIME DATETIME,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    REMARKS VARCHAR(1000),
    PRIMARY KEY (ID)
);

/*角色机构表*/
CREATE TABLE ROLE_ORGANIZATION
(
	ID VARCHAR(32) NOT NULL,
    ROLE_ID VARCHAR(32) NOT NULL,
    ORGANIZATION_ID VARCHAR(32) NOT NULL,
    ACTIVE INT,
    VERSION INT,
    CREATE_TIME DATETIME,
    UPDATE_TIME DATETIME,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    REMARKS VARCHAR(1000),
    PRIMARY KEY (ID)
);

/*用户角色表*/
CREATE TABLE USER_ROLE
(
	ID VARCHAR(32) NOT NULL,
	USER_ID VARCHAR(32) NOT NULL,
    ROLE_ID VARCHAR(32) NOT NULL,
    ACTIVE INT,
    VERSION INT,
    CREATE_TIME DATETIME,
    UPDATE_TIME DATETIME,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    REMARKS VARCHAR(1000),
    PRIMARY KEY (ID)
);

/*指静脉表*/
CREATE TABLE FINGERVEIN
(
    ID VARCHAR(32) NOT NULL,
    SEQ VARCHAR(10),
    STATUS CHAR(1),
    FEATURE BLOB,
    EMPLOYEE_ID VARCHAR(32) NOT NULL,
    ACTIVE INT,
    VERSION INT,
    CREATE_TIME DATETIME,
    UPDATE_TIME DATETIME,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    REMARKS VARCHAR(1000),
    PRIMARY KEY (ID)
);

/*识别日志表*/
CREATE TABLE RECOGNITION_LOG
(
    ID VARCHAR(32) NOT NULL,
    NAME VARCHAR(100),
    CODE VARCHAR(100),
    SEQ VARCHAR(10),
    THRESHOLD VARCHAR(10),
    INDEXED INT,
    TYPE CHAR(1),
    STATUS CHAR(1),
    ORG_NAME VARCHAR(100),
    IPADDR VARCHAR(100),
    FILE_PATH VARCHAR(100),
    TERMINAL_ID VARCHAR(32),
    EMPLOYEE_ID VARCHAR(32),
    FINGERVEIN_ID VARCHAR(32),
    ACTIVE INT,
    VERSION INT,
    CREATE_TIME DATETIME,
    UPDATE_TIME DATETIME,
    CREATE_BY VARCHAR(100),
    UPDATE_BY VARCHAR(100),
    REMARKS VARCHAR(1000),
    PRIMARY KEY (ID)
);